# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: gomoku_arm
  joint_model_group_pose: home_zero_virtual
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - join_1
    - joint_2
    - joint_3
    - gripper_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: gomoku_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - join_1
      - joint_2
      - joint_3
      - gripper_joint
gomoku_controller_jointpos:
  type: position_controllers/JointPositionController
  joints:
    - join_1
    - joint_2
    - joint_3
    - gripper_joint
  gains:
    join_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1